version: '3.8'

services:

  app:
    build: .
    container_name: teammate-finder-app
    ports:
      - "10500:4000" # <--- ЗОВНІ 10500 -> ВНУТРІШНІЙ 4000
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongo:27017/teammate_finder_db
      # Сюди можна додати і GOOGLE_CLIENT_ID, якщо треба, або використати .env файл
    depends_on:
      - mongo
    restart: always

  # --- База Даних (MongoDB) ---
  mongo:
    image: mongo:6.0
    container_name: teammate-finder-db
    ports:
      - "27017:27017" # Це стандартний порт Монго (замість 3306 у MySQL)
    volumes:
      - mongo-data:/data/db # Щоб дані не зникли при перезапуску
    restart: always

volumes:
  mongo-data: